### PR TITLE
Fix: Update 'current' to Reflect Last Overlay When Closing Intermediate Overlays

### LINKED ISSUE #44: Is the intended behavior that firing a `close` event does not change `current`?
## Question

As I looked at the code, I had the following questions.

Neither `overlay.close()` nor `close` will change the `current`.
When I saw the name `current`, I thought it was related to the `overlay` that is currently `open`, but it's not.
Currently, `current` only changes in relation to `unmount`.

Is this the intended behavior?

## Test

I ran the following tests.

```tsx
import { act, render, screen } from '@testing-library/react';
import { useEffect, type PropsWithChildren } from 'react';
import { afterEach, describe, expect, it } from 'vitest';
import { OverlayProvider, useCurrentOverlay } from './context';
import { overlay } from './event';

afterEach(() => {
  overlay.unmountAll();
});

describe('overlay object', () => {
  it('overlay.close current test', async () => {
    const wrapper = ({ children }: PropsWithChildren) => <OverlayProvider>{children}</OverlayProvider>;

    const testContent1 = 'context-modal-test-content-1';
    const testContent2 = 'context-modal-test-content-2';
    const closeCurrent = 'close-current';

    let current: string | null = null;

    const Component = () => {
      current = useCurrentOverlay();

      useEffect(() => {
        overlay.open(
          ({ isOpen }) => {
            return <>{isOpen && <p>{testContent1}</p>}</>;
          },
          { overlayId: 'overlayId1' }
        );

        overlay.open(
          ({ isOpen, close }) => {
            return <>{isOpen && <p onClick={close}>{testContent2}</p>}</>;
          },
          { overlayId: 'overlayId2' }
        );
      }, []);

      return <div onClick={() => overlay.close(current!)}>{closeCurrent}</div>;
    };

    const renderComponent = render(<Component />, { wrapper });

    const testContentElement2 = await renderComponent.findByText(testContent2);
    const closeCurrenteElement = await renderComponent.findByText(closeCurrent);

    act(() => {
      testContentElement2.click(); // I expect `current` to change overlayId1.
      closeCurrenteElement.click(); // I expect `testContent1` to be closed.
    });

    expect(screen.queryByText(testContent1)).not.toBeInTheDocument();
    expect(screen.queryByText(testContent2)).not.toBeInTheDocument();
    expect(current).toBe(null);
  });
});
```

### Result

The `context-modal-test-content-1` still exists.

스크린샷 2024-07-10 오후 7 17 57

The `current` returns `overlayId2`, not `null`.

스크린샷 2024-07-10 오후 7 18 35

### PR DESCRIPTION
**Pull request by jungpaeng**
### Description
This PR addresses an issue where the 'current' overlay does not update to the last overlay when an intermediate overlay is closed. This behavior can lead to inconsistencies in the UI state.

### Changes
- Modified the reducer logic to ensure 'current' is correctly set to the last overlay when closing an intermediate overlay.
- Added checks to handle cases where the overlay order is modified.

### Motivation and Context
The previous implementation did not account for scenarios where closing an intermediate overlay should update the 'current' overlay to reflect the last one in the order. This fix ensures that the 'current' overlay always points to the last opened overlay, maintaining consistent UI behavior.

### How Will This Be Tested?
- Tested by manually opening and closing multiple overlays in various orders to ensure 'current' updates correctly.
- I plan to add unit tests to verify the reducer logic for maintaining the correct 'current' overlay.

### Related Issues
Fixes #44

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: packages/src/context/reducer.ts [hunk 1]
```diff
@@ -33,12 +33,29 @@ export function overlayReducer(state: OverlayData, action: OverlayReducerAction)
...
+      const targetIndexInOpenedList = openedOverlayOrderList.findIndex((item) => item === action.overlayId);
+
+      /**
+       * @description If closing the last overlay, specify the overlay before it.
+       * @description If closing intermediate overlays, specifies the last overlay.
+       *
+       * @example open - [1, 2, 3, 4]
+       * close 2 => current: 4
+       * close 4 => current: 3
+       * close 2 => current: 1
```
Comment (jgjgill) [inline packages/src/context/reducer.ts:48]: Oh, I think `close 3 => current: 1` is correct.
I'll write a PR.

**Comment by jgjgill** [comment]
Oh, thanks for the thorough check. 😂
