### PR TITLE
fix: Enhance Overlay State Management and Prevent Duplicate Entries

### LINKED ISSUE #46: Suggestion: Prevent `ADD` action if the custom-id already exists.
## Problem situation

When specifying `custom-id` separately on `overlay.open`, multiple occurrences of that event will result in an error.

**Example code**

```tsx
<button
  onClick={() => {
    overlay.open(
      ({ isOpen, close, unmount }) => {
        return (
          <CenterModal isOpen={isOpen} onExit={unmount}>
            <div>
              <p>MODAL CONTENT</p>
              <button onClick={close}>close modal</button>
            </div>
          </CenterModal>
        );
      },
      { overlayId: 'overlayid-1' }
    );
  }}
>
  open center modal
</button>
```

**Demo**

https://github.com/toss/overlay-kit/assets/79239852/d4dea1ae-a85e-4370-bcc0-398943da2588

## Cause of the problem

This appears to be caused by the same `overlayId` already existing in the `overlayOrderList`.

## Workaround

I thought of adding the following code in the `ADD` action.
If the `overlayId` already exists, return the existing `state`.

**reducer.ts**

```ts
    case 'ADD': {
      if (state.overlayOrderList.includes(action.overlay.id)) {
        return state;
      }

      return {
        current: action.overlay.id,
        overlayOrderList: [...state.overlayOrderList, action.overlay.id],
        overlayData: {
          ...state.overlayData,
          [action.overlay.id]: action.overlay,
        },
      };
    }
```

**Expected behavior**

https://github.com/toss/overlay-kit/assets/79239852/e2657958-cac3-43fa-b429-1dfb027ca83f

If you think the suggestion is appropriate, would you mind if I add a feature fix and test code? 🧐

### PR DESCRIPTION
**Pull request by jungpaeng**
## Description

This change enhances the overlay state management to ensure overlays maintain the correct state when closed and reopened, and prevents duplicate overlay entries. It addresses issues with the overlay's `current` state not updating correctly in certain scenarios.

**Related Issue:** Fixes #46 

## Changes

- Added `current` state to track the current overlay in `OverlayProvider` and `ContentOverlayController`.
- Implemented logic in `ContentOverlayController` to maintain overlay state correctly when an overlay is closed and reopened without unmounting.
- Updated `ContentOverlayController` to use `useRef` for tracking the previous `current` state and triggering the `onMounted` callback appropriately.
- Improved type definitions for `ContentOverlayControllerProps` and `OverlayControllerProps` to include the new `current` state.

## Motivation and Context

The changes are necessary to ensure that the overlay state is correctly managed, especially when overlays are closed and reopened without being unmounted. This prevents issues where overlays might not display the correct state or duplicate entries could occur.

## How Has This Been Tested?

- Tested by manually opening and closing multiple overlays in various orders to ensure `current` updates correctly.
- Added unit tests to verify the reducer logic for maintaining the correct `current` overlay.
- Conducted tests in a development environment to ensure no new warnings are generated and all functionalities work as expected.

## Screenshots (if appropriate):

https://github.com/user-attachments/assets/6a10770c-4f70-4d8a-97f4-98121aebb221

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

## Checklist

- [x] I have performed a self-review of my own code.
- [x] My code is commented, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Further Comments

N/A

### CODE REVIEW

File: packages/src/context/provider.tsx [hunk 1]
```diff
@@ -53,14 +55,27 @@ type ContentOverlayControllerProps = {
...
+  /**
+   * @description Executes when closing and reopening an overlay without unmounting.
+   */
+  if (prevCurrent.current !== current) {
+    prevCurrent.current = current;
+
+    if (current === overlayId) {
+      onMountedRef.current();
+    }
+  }
```
Comment (jgjgill) [inline packages/src/context/provider.tsx:77]: This part needed some work too. I learned it thanks to you. 🧐

File: packages/src/context/reducer.ts [hunk 2]
```diff
@@ -11,9 +11,18 @@ export type OverlayReducerAction =
...
+        throw new Error('The same overlayId exists.');
+      }
+
       return {
         current: action.overlay.id,
-        overlayOrderList: [...state.overlayOrderList, action.overlay.id],
+        /**
+         * @description Brings the overlay to the front when reopened after closing without unmounting.
+         */
+        overlayOrderList: [...state.overlayOrderList.filter((item) => item !== action.overlay.id), action.overlay.id],
```
Comment (jgjgill) [inline packages/src/context/reducer.ts:25]: good! 👍

**Review by jgjgill — APPROVED** [review]
I've checked. Thank you for your efforts. 🙇‍♂️

File: packages/src/context/provider.tsx (hunk 1 above)
Comment (ojj1123) [reply packages/src/context/provider.tsx:77]: I don't understand why this logic is needed.
Could anyone explain the reason? Are there the edge cases?

Comment (jungpaeng) [reply packages/src/context/provider.tsx:77]: The reason this is necessary is because the handling of open modals is performed during the ADD stage in the reducer.

Let’s examine the flow when an overlay is first opened:

1. Calling overlay.open triggers `dispatch(overlays, { type: 'ADD' })`.
2. The reducer then adds the `overlayId` to the `overlayOrderList`.
3. The `overlayId` added to the `overlayOrderList` renders the `ContentOverlayController` component.
4. The `ContentOverlayController` component, via `useEffect`, calls `dispatch(overlays, { type: 'OPEN' })` for the newly added overlay.

However, if the overlay is closed without unmounting, the `overlayId` is not re-added to the `overlayOrderList`, and the key remains the same. Therefore, it is treated as the same component as before, and step 4 does not occur, resulting in the `isOpen` value not changing to `true`.

To address the edge case where an overlay is closed without unmounting and then reopened, the `ContentOverlayController` now checks the `current` value, which indicates the topmost open overlay.
If the current value matches the overlayId that the `ContentOverlayController` holds, it recognizes that the `ADD` reducer has been executed and proceeds to trigger the `OPEN` reducer.

File: packages/src/context/reducer.ts [hunk 3]
```diff
@@ -11,9 +11,18 @@ export type OverlayReducerAction =
 export function overlayReducer(state: OverlayData, action: OverlayReducerAction): OverlayData {
   switch (action.type) {
     case 'ADD': {
+      const isExisted = state.overlayOrderList.includes(action.overlay.id);
+
+      if (isExisted && state.overlayData[action.overlay.id].isOpen === true) {
+        throw new Error('The same overlayId exists.');
```
Comment (ojj1123) [inline packages/src/context/reducer.ts:17]:
```suggestion
        throw new Error('You can't open the multiple overlays with the same overlayId. Please set a different id.');
```

I think it is better to make it clear to say the user that you can't open the multiple overlays with the same id.

**Review by ojj1123 — COMMENTED** [review]
Thanks for your great works!

**Review by ojj1123 — APPROVED** [review]
Look good to me 👍
